apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: lz-vmcluster
spec:
  # Add fields here
  # https://docs.victoriametrics.com/operator/api.html#vmclusterspec
  retentionPeriod: "12"
  vmstorage:
    # https://docs.victoriametrics.com/operator/api.html#vmstorage
    replicaCount: 2
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10G
#          storageClassName: linode-block-storage-retain
          storageClassName: linode-block-storage
    storageDataPath: /vm-data
  vmselect:
    replicaCount: 2
  vminsert:
    replicaCount: 2